version: '2'
services:
  portainer:
    image: portainer/portainer:arm
    container_name: Portainer
    expose:
      - 9000
    ports:
      - 9000:9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - VIRTUAL_HOST=app.mydomain.com
      - VIRTUAL_PORT=9000
      - VIRTUAL_NETWORK=proxy-network

networks:
  default:
    external:
      name: proxy-network

